### ISSUE TITLE
PySimpleGUI has changed business model

### ISSUE THREAD

**Issue by Gikkman** [preshtildeath/print-proxy-prep#4]
I made a clean install recently, and the latest version of PySimpleGUI gives you 30 days of trial, and then you have to register an account to use it. So I suggest pinning the version in the `requirements.txt` to 4.59.0 ('cause they janked the more recent releases).

https://pypi.org/project/PySimpleGUI/ and https://pypi.org/project/PySimpleGUI/#history

**Comment by urza-lab** [comment]
As a non-commercial user, you can have a free license for one year with free renewal thereafter.

**Comment by Gikkman** [comment]
I know there's several people with very limited programming experience that use this project, and they won't necessarily know what to do, or if it is normal/expected. Its not directly a normal procedure when using small opensource projects like this. I am not saying you're wrong, you can get a free license. But I think it makes it challenging for inexperienced users.

**Comment by Malacath-92** [comment]
I've spent some of my freetime to rewrite all the GUI in Qt. If you wanna try it, it's on my branch here: https://github.com/Malacath-92/print-proxy-prep/tree/QtPort
![image](https://github.com/user-attachments/assets/2c38a324-f8a6-4add-b80b-6d037592e1fd)

**Comment by Malacath-92** [comment]
Also just a note, I couldn't pin the old version for PySimpleGUI last I tried 'cause they purged their old versions from the pip repo.

**Comment by dyslxeic** [comment]
> I've spent some of my freetime to rewrite all the GUI in Qt. If you wanna try it, it's on my branch here: https://github.com/Malacath-92/print-proxy-prep/tree/QtPort ![image](https://private-user-images.githubusercontent.com/30243536/363099345-2c38a324-f8a6-4add-b80b-6d037592e1fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTgxNDksIm5iZiI6MTcyODMxNzg0OSwicGF0aCI6Ii8zMDI0MzUzNi8zNjMwOTkzNDUtMmMzOGEzMjQtZjhhNi00YWRkLWI4MGItNmQwMzc1OTJlMWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE2MTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNjk4YjhhZDJjMDliYTA5MTE0M2I2MmIzOWUwNzdmM2FhYzUyNWY1OTljZDZhY2NlOGQxYTc4NGI0ZTU5YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pXTlJqstTIRdLXQHJS-vvnI0g7JypQcxdyHoOpcQM5g)

I tried using your forked version as for some reason the original version goes not responding whenever it tries to render, however for yours it did successfully crop the images, and create the image.cache however after this it failed and never created a print.json file.

here's the error details from cmd:
`Error: Failed loading project... Resetting...
Traceback (most recent call last):
  File "C:\Users\XXX\MTG Proxies\print-proxy-prep-QtPort\main.py", line 38, in <module>
    window = gui_qt.window_setup(app, print_dict, img_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\MTG Proxies\print-proxy-prep-QtPort\gui_qt.py", line 1589, in window_setup
    application.set_window(window)
  File "C:\Users\XXX\MTG Proxies\print-proxy-prep-QtPort\gui_qt.py", line 61, in set_window
    window.restoreGeometry(self._window_geometry)
                           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrintProxyPrepApplication' object has no attribute '_window_geometry'`

@Malacath-92

**Comment by Malacath-92** [comment]
@dyslxeic I believe I have pushed a fix for this just now, however I can't test right now so if you wanna wait until I confirm I will get back to you tomorrow

**Comment by Malacath-92** [comment]
@dyslxeic this should definitely be fixed now

**Comment by dyslxeic** [comment]
Thanks, working!
